---
name: update-tfswitch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Update system and install additional packages
        run: pacman -Syyu --noconfirm git jq pacman-contrib

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Adding working directory to the git global config as a safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update packages
        run: ./.github/scripts/update-tfswitch.sh

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_PKGBUILDS }}
          branch: update-pkgbuild/tfswitch
          delete-branch: true
          author: ${{ secrets.GIT_USER_NAME }} <${{ secrets.GIT_USER_EMAIL }}>
          committer: ${{ secrets.GIT_USER_NAME }} <${{ secrets.GIT_USER_EMAIL }}>
          title: "chore(tfswitch): bump version to ${{ env.LATEST_VERSION }}"
          commit-message: "chore(tfswitch): bump version to ${{ env.LATEST_VERSION }}"
          body: ""

      - name: Enable auto-merge
        run: gh pr merge --auto --rebase "${{ steps.cpr.outputs.pull-request-url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
